build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

checks:
    php: true
filter:
    excluded_paths: [vendor/*, tests/*]
tools:
    external_code_coverage: true
