checks:
    php: true

filter:
    excluded_paths:
        - tests/*
tools:
    external_code_coverage:
        timeout: 1800
        runs: 2

build:
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.txt'
                coverage:
                    file: 'coverage.txt'
                    format: 'clover'
