version: '3.7'
services:
  # web:
  #   build:
  #       context: ./
  #       dockerfile: Dockerfile.web
  #   container_name: nginx
  #   ports:
  #       - 80:80
  database:
    image: mysql:5.7.27
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    env_file: ./env/.env.mysql
    volumes:
        - ./mysql_data:/var/lib/mysql
        - ./mysql-files/setup.sql:/docker-entrypoint-initdb.d/setup.sql
        - ./serverConfiguration/deploy/my.cnf:/etc/mysql/my.cnf
    restart: always
    ports:
        - "3306:3306"
  tika:
    image: logicalspark/docker-tikaserver
    container_name: tika_service
    restart: always
    ports:
        - "9998:9998"
  app:
    build:
        context: ./
        dockerfile: Dockerfile
    container_name: ccdt_php
    volumes:
        - /data/storage:/var/www/storage
        - ./env:/env
        - ./scripts:/var/www/scripts
        - ./src/project-css:/var/www        
    env_file: ./env/.env.prod
    restart: always
    ports:
        - "9000:9000"
