version: '3.1'
services:
#    web:
#        build:
#            context: ./
#            dockerfile: serverConfiguration/deploy/prod.web.docker
#        container_name: nginx
#        ports:
#          - 80:80
    database:
        image: mysql:5.7.27
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        env_file: ./src/project-css/.env.mysql
        volumes:
            - ./mysql_data:/var/lib/mysql
            - ./mysql-files/setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - ./serverConfiguration/deploy/my.cnf:/etc/mysql/my.cnf
        restart: always
        ports:
            - "3306:3306"
    tika:
        image: logicalspark/docker-tikaserver
        container_name: tika_service
        restart: always
        ports:
            - "9998:9998"
    app:
        build:
            context: ./
            dockerfile: serverConfiguration/deploy/prod.app.docker
        container_name: ccdt_php
        volumes:
            - /data/storage:/var/www/storage
        env_file: ./src/project-css/.env.prod
        restart: always
        ports:
          - "9000:9000"
