FROM php:7.3.12-fpm

WORKDIR /var/www
ADD src/project-css /var/www

# Fix debconf warnings upon build
ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    default-mysql-client \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    libzip-dev \
    jpegoptim optipng pngquant gifsicle \
    unzip \
    git \
    curl \ 
    wget \
    graphviz

# Install xdebug used for phpunit coverage reports
RUN yes | pecl install xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=off" >> /usr/local/etc/php/conf.d/xdebug.ini

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install extensions
RUN docker-php-ext-install pdo_mysql mbstring zip exif pcntl \
    && docker-php-ext-configure gd --with-gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ --with-png-dir=/usr/include/ \
    && docker-php-ext-install gd

# install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Install nodejs LTS
ENV	VERSION='14'
RUN curl -sL https://deb.nodesource.com/setup_${VERSION}.x | bash - \
	&& apt -y install build-essential \
	&& apt -y install nodejs \
	&& npm i -g npm

# install gulp
RUN npm install --global gulp-cli   

# Install phpDocumentor with Pear
#RUN wget https://pear.phpdoc.org/channel.xml \
#    && pear channel-add ./channel.xml
#RUN wget https://github.com/phpDocumentor/phpDocumentor2/releases/download/v2.9.0/phpDocumentor-2.9.0.tgz \
#    && pear install phpDocumentor-2.9.0.tgz

# set php
ADD ./serverConfiguration/php.ini /usr/local/etc/php/

EXPOSE 9000

ADD ./scripts/startup-dev.sh /usr/bin/
RUN chmod -v +x /usr/bin/startup-dev.sh
ENTRYPOINT ["/usr/bin/startup-dev.sh"]