version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: serverConfiguration/deploy/prod.web.docker
        container_name: nginx
        ports:
          - 80:80
    database:
        image: mysql:5.7.27
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        env_file: ./src/project-css/.env.mysql
        volumes:
            - ./mysql_data:/var/lib/mysql
            - ./mysql-files/setup.sql:/docker-entrypoint-initdb.d/setup.sql
            - ./serverConfiguration/deploy/my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
    tika:
        image: logicalspark/docker-tikaserver
        container_name: tika_service
        ports:
            - "9998:9998"
    app:
        build:
            context: ./
            dockerfile: serverConfiguration/deploy/prod.app.docker
        container_name: rockefeller-css_php
        volumes:
            - ./src/project-css:/var/www
        env_file: ./src/project-css/.env.prod
        ports:
          - "9001:9000"
    laravel-queue:
        restart: always
        build:
            context: ./
            dockerfile: serverConfiguration/deploy/prod.app.docker
        command: php artisan queue:work
        volumes:
            - ./src/project-css:/var/www
        env_file: ./src/project-css/.env.prod