version: '3'
services:
    database:
        image: mysql:5.7.27
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        env_file: ./src/project-css/.env.mysql
        volumes:
            - ./mysql_data:/var/lib/mysql
            - ./mysql-files/setup.sql:/docker-entrypoint-initdb.d/setup.sql
        ports:
            - "3306:3306"
    tika:
        image: trmccormick/tika
        container_name: tika_service
        ports:
            - "9998:9998"
    app:
        build: 
          context: ./
          dockerfile: Dockerfile
        container_name: rockefeller-css_php
        volumes:
            - ./src/project-css/storage:/var/www/storage
        env_file: ./src/project-css/.env.prod
        ports:
          - "9000:9000"
